# Generated by Django 4.1.7 on 2023-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField()),
                ('rating_message', models.TextField()),
            ],
        ),
    ]
