# Generated by Django 4.1.7 on 2023-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
